kpop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('stats.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stats/urls.py
from django.urls import path

from . import views

app_name = 'stats'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('categories/', views.CategoriesView.as_view(), name='categories'),
    path('groups/', views.GroupsView, name='groups'),
    path('groups/hottest', views.GroupsViewHottest, name='hottest'),
    path('groups/alphabetical', views.GroupsViewAlpha, name='alphabetical'),
    path('groups/oldest', views.GroupsViewOldest, name='oldest'),
    path('groups/newest', views.GroupsViewNewest, name='newest'),
    path('profile/<int:pk>/<str:name>', views.ProfileView, name='profile'),
    path('addvideos/', views.AddVideos.as_view(), name='addvideos'),
    path('addvideos/<int:pk>/<str:name>', views.GroupEdit, name='groupedit'),
    #path('delete/', views.deleteVids, name='deletevids'),
    path('graph/<str:gender>', views.GraphView, name='graph'),
    path('compare/<int:pk>/<str:name>', views.CompareView, name='compare'),
    path('compare/hottest/<int:pk>/<str:name>', views.CompareViewHottest, name='comparehottest'),
    path('compare/alphabetical/<int:pk>/<str:name>', views.CompareViewAlpha, name='comparealphabetical'),
    path('compare/oldest/<int:pk>/<str:name>', views.CompareViewOldest, name='compareoldest'),
    path('compare/newest/<int:pk>/<str:name>', views.CompareViewNewest, name='comparenewest'),
    path('comparing/<int:pk>/<int:pk2>', views.ComparingView, name='comparing'),
    path('data/', views.DataView, name='data'),
    path('data/gender/', views.GenderDataView, name='genderData'),
    path('data/company/', views.CompanyDataView, name='companyData'),
]

stats/models.py
from django.db import models
from django.utils import timezone
from . import yt
import datetime

# model for storing artist information
class Group(models.Model):
    name = models.CharField(max_length=200)
    debut_date = models.DateField('debut date')
    video_count = models.IntegerField(default=0)
    total_view_count = models.BigIntegerField(default=0)
    company = models.CharField(max_length=200)
    current_member_count = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='gallery')
    yt_channel_id = models.CharField(max_length=200)
    pic_url = models.CharField(max_length=200, null=True)

    GIRL = 'G'
    BOY = 'B'
    MIX = 'M'
    GENDER_CHOICES = (
        (GIRL, 'Female'),
        (BOY, 'Male'),
        (MIX, 'Mixed')
    )
    gender = models.CharField(max_length=200, choices=GENDER_CHOICES, default=GIRL)

    def __str__(self):
        return self.name

    def is_solo(self):
        return (self.current_member_count == 1)

# model for storing music video information
class Video(models.Model):
    # give each video object an artist
    group = models.ForeignKey(Group, related_name='videos', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    upload_date = models.DateField('upload date')
    view_count = models.BigIntegerField(default=0)
    yt_video_id = models.CharField(max_length=200)
    thumbnail_url = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.title

    # updates view information using Youtube api
    def updateViews(self):
        self.view_count = yt.YTapi.getViewCount(yt_id=self.yt_video_id)[0]
        self.save()

    # update picture/thumbnail information using Youtube api
    def updatePic(self):
        self.thumbnail_url = yt.YTapi.getViewCount(yt_id=self.yt_video_id)[1]
        self.save()

stats/forms.py
from django import forms
from .models import Video

class VidForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ('group','title','upload_date','yt_video_id','thumbnail_url')

stats/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.forms import modelformset_factory, inlineformset_factory
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models.functions import TruncMonth, ExtractMonth, ExtractYear
from django.db.models import Count, Sum
from datetime import datetime, timedelta
import operator
from .models import Group, Video
from . import vids
from .forms import VidForm

# used for authorization of staff pages
class AdminStaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

# home view
def IndexView(request):
    object_list = Group.objects.all()

    '''
    object_list: all elements of Group model
    '''
    return render(request, 'stats/index.html', {"object_list": object_list, "bp":bp})

# about view
class AboutView(generic.ListView):
    template_name = 'stats/about.html'
    model = Group

# view for comparing 2 artists
def ComparingView(request, pk, pk2):

    g1 = Group.objects.get(pk=pk)
    g2 = Group.objects.get(pk=pk2)

    g1stats = [Video.objects.filter(group=g1).order_by('view_count').reverse()[0],
               Video.objects.filter(group=g1).order_by('upload_date').reverse()[0],
               Video.objects.filter(group=g1).order_by('upload_date')[0]]

    g2stats = [Video.objects.filter(group=g2).order_by('view_count').reverse()[0],
               Video.objects.filter(group=g2).order_by('upload_date').reverse()[0],
               Video.objects.filter(group=g2).order_by('upload_date')[0]]

    dV = [['Jan', 0, 0], ['Feb', 0, 0], ['Mar', 0, 0], ['Apr', 0, 0], ['May', 0, 0], ['Jun', 0, 0], ['Jul', 0, 0],
          ['Aug', 0, 0], ['Sep', 0, 0], ['Oct', 0, 0], ['Nov', 0, 0], ['Dec', 0, 0]]

    dateVids1 = Video.objects.filter(group=g1).annotate(month=ExtractMonth('upload_date')).values('month').annotate(
        c=Count('id')).values('month', 'c')

    for v in dateVids1:
        dV[v['month'] - 1][1] = v['c']

    dateVids2 = Video.objects.filter(group=g2).annotate(month2=ExtractMonth('upload_date')).values('month2').annotate(
        c2=Count('id')).values('month2', 'c2')

    for v in dateVids2:
        dV[v['month2'] - 1][2] = v['c2']

    yV1 = Video.objects.filter(group=g1).annotate(year=ExtractYear('upload_date')).values('year').annotate(
        cy=Sum('view_count')).values('year', 'cy')
    yV2 = Video.objects.filter(group=g2).annotate(year=ExtractYear('upload_date')).values('year').annotate(
        cy2=Sum('view_count')).values('year', 'cy2')

    hold = []
    for y in yV1:
        hold.append(y['year'])
    for y in yV2:
        hold.append(y['year'])

    last = max(hold)
    first = min(hold)

    yV = list(range(first, last+1))

    for i, item in enumerate(yV):
        yV[i] = [item, 0, 0]

    for y in yV1:
        for item in yV:
            if y['year'] == item[0]:
                item[1] = y['cy']

    for y in yV2:
        for item in yV:
            if y['year'] == item[0]:
                item[2] = y['cy2']

    '''
    g1, g2: element of first and second group
    g1stats, g2stats: view count and upload dates for first and second group
    dV: g1,g2 data by month
    yV: g1,g2 data by year
    '''
    return render(request, 'stats/comparing.html',{"g1": g1, "g2": g2, "g1stats": g1stats, "g2stats": g2stats, "dV": dV,
                                                   "yV": yV})
# view for selecting second group to compare with
def CompareView(request, pk, name):
    object_list = Group.objects.exclude(pk=pk).order_by('total_view_count').reverse()
    sort = "Most Viewed"
    company_list = Group.objects.exclude(pk=pk).order_by('company').distinct('company')

    '''
    name: group name
    opk: primary key for group
    object_list: elements of Group model excluding 'opk' group
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements excluding 'opk' group
    '''
    return render(request, 'stats/compare.html', {"name": name, "opk": pk, "object_list": object_list, "sort": sort,
                                                  "company_list": company_list})

# view for displaying artists
def GroupsView(request):
    object_list = Group.objects.all().order_by('total_view_count').reverse()
    sort = "Most Viewed"
    company_list = Group.objects.order_by('company').distinct('company')

    search_term = ''

    # searching capabilities by artist name or company name
    if 'search' in request.GET:
        search_term = request.GET['search']
        object_list = Group.objects.filter(name__icontains=search_term)
        ol2 = Group.objects.filter(company__icontains=search_term)
        object_list = object_list.union(ol2).order_by('total_view_count').reverse()

    '''
    object_list: elements of Group model
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements
    search_term: item searched for by user
    '''
    return render(request, 'stats/groups.html', {"object_list": object_list, "sort": sort, "company_list": company_list,
                                                 "search_term": search_term})

# view for selecting second group to compare with sorted by hottest
def CompareViewHottest(request, pk, name):
    start_date = timezone.now()-timezone.timedelta(days=90)
    end_date = timezone.now()
    group = Group.objects.exclude(pk=pk).order_by('total_view_count').reverse()
    hot = []
    for i,g in enumerate(group):
        hot.append([g, 0])
        if Video.objects.filter(group=g, upload_date__range=(start_date, end_date)).order_by('upload_date').reverse():
            for v in Video.objects.filter(group=g, upload_date__range=(start_date, end_date)).order_by('upload_date')\
                    .reverse():
                hot[i][1] += v.view_count
    hot.sort(key=operator.itemgetter(1), reverse=True)
    object_list = []
    for h in hot:
        object_list.append(h[0])
    sort = "Hottest"
    company_list = Group.objects.exclude(pk=pk).order_by('company').distinct('company')

    '''
    name: group name
    opk: primary key for group
    object_list: elements of Group model sorted by 'hottest'
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements
    '''
    return render(request, 'stats/compare.html', {"name": name, "opk": pk, "object_list": object_list, "sort": sort,
                                                  "company_list": company_list})

# view for displaying artists sorted by hottest
def GroupsViewHottest(request):
    start_date = timezone.now()-timezone.timedelta(days=90)
    end_date = timezone.now()
    group = Group.objects.all().order_by('total_view_count').reverse()
    hot = []
    for i,g in enumerate(group):
        hot.append([g, 0])
        if Video.objects.filter(group=g, upload_date__range=(start_date, end_date)).order_by('upload_date').reverse():
            for v in Video.objects.filter(group=g, upload_date__range=(start_date, end_date)).order_by('upload_date')\
                    .reverse():
                hot[i][1] += v.view_count
    hot.sort(key=operator.itemgetter(1), reverse=True)
    object_list = []
    for h in hot:
        object_list.append(h[0])
    sort = "Hottest"
    company_list = Group.objects.order_by('company').distinct('company')

    '''
    object_list: elements of Group model
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements
    '''
    return render(request, 'stats/groups.html', {"object_list": object_list, "sort": sort,
                                                 "company_list": company_list})

# view for selecting second group to compare with sorted by alphabetical
def CompareViewAlpha(request, pk, name):
    object_list = Group.objects.exclude(pk=pk).order_by('name')
    sort = "Alphabetical"
    company_list = Group.objects.exclude(pk=pk).order_by('company').distinct('company')

    '''
    name: group name
    opk: primary key for group
    object_list: elements of Group model sorted by 'hottest'
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements
    '''
    return render(request, 'stats/compare.html', {"name": name, "opk": pk, "object_list": object_list, "sort": sort,
                                                  "company_list": company_list})

# view for displaying artists sorted by alphabetical
def GroupsViewAlpha(request):
    object_list = Group.objects.all().order_by('name')
    sort = "Alphabetical"
    company_list = Group.objects.order_by('company').distinct('company')

    '''
    object_list: elements of Group model
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements
    '''
    return render(request, 'stats/groups.html', {"object_list": object_list, "sort": sort,
                                                 "company_list": company_list})

# view for selecting second group to compare with sorted by oldest
def CompareViewOldest(request, pk, name):
    object_list = Group.objects.exclude(pk=pk).order_by('debut_date')
    sort = "Oldest"
    company_list = Group.objects.exclude(pk=pk).order_by('company').distinct('company')

    '''
    name: group name
    opk: primary key for group
    object_list: elements of Group model sorted by 'hottest'
    sort: setting for sort button
    company_list: distinct 'company' elements of Group model elements
    '''
    return render(request, 'stats/compare.html', {"name": name, "opk": pk, "object_list": object_list, "sort": sort,
                                                  "company_list": company_list})

stats/templates/stats/about.html
<!doctype html>

{% load static %}

<html>

    <head>
        <meta charset="'utf-8">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'stats/about.css' %}">
        <title></title>
    </head>

    <body>

        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <a href="{% url 'stats:index' %}" class="navbar-brand">Kpop-Numbers</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:groups' %}">Artists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:graph' 'all' %}">Graphs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:data' %}">Data</a>
                    </li>
                </ul>
            </div>
            <form action="/groups/" class="form-inline my-2 my-lg-0">
                <input id="search_box" name="search" class="form-control mr-sm-2" type="search" placeholder="Search for artist" aria-label="Search">
                <button id="search_submit" class="btn btn-outline-warning my-2 my-sm-0" type="search">Search</button>
            </form>
        </nav>

        <div class="container jumbotron">
            <div  align="left">
                <h2>Welcome to Kpop-Numbers!</h2>
                <h3>&nbsp;</h3>
                <h5>I built this website as a tool for monitoring and visualizing Youtube music video views of popular
                    Kpop Artists. It is still a work in progress, but I hope one day it will be seamless and easy
                    to use for everyone. Please let me know if there are any bugs or improvements you would like to
                    bring to my attention. Thank you!</h5>
                <h3>&nbsp;</h3>
                <h3>&nbsp;</h3>
                <h3>Q&A:</h3>
                <h3>&nbsp;</h3>
                <h4>How often are music video views updated?</h4>
                <h5>The data for each music video is updated every midnight pacific time using Youtube's api</h5>
                <h3>&nbsp;</h3>
                <h4>I don't see my favorite artist. Will you be adding more?</h4>
                <h5>Contact me with any missing/incorrect artists or information on this website</h5>
                <h3>&nbsp;</h3>
                <h4>How is this tool useful?</h4>
                <h5>By visualizing music video views, it is easier to see trends or correlations with popularity. I
                    hope to add explanations for the graphs and charts in the future to help visitors understand what
                    they are seeing. Additionally, I plan to apply data analytics to make predictions about a group's
                    future popularity based on multiple of factors.</h5>
            </div>
        </div>

        <!-- Footer -->
        <footer class="page-footer font-small blue pt-4">
          <!-- Footer Links -->
          <div class="container-fluid text-center text-md-left">
            <!-- Grid row -->
            <div class="row">
              <!-- Grid column -->
              <div class="col-md-6 mt-md-0 mt-3">
                <!-- Content -->
                <h5 class="text-uppercase">Contact</h5>
                <p>aaronmitchellharris@gmail.com</p>
              </div>
              <!-- Grid column -->
              <hr class="clearfix w-100 d-md-none pb-3">
              <!-- Grid column -->
              <div class="col-md-3 mb-md-0 mb-3">
                  <img src="https://developers.google.com/youtube/images/developed-with-youtube-sentence-case-dark.png" alt="..." width="400" height="143">
                <!-- Links
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                  <li>
                    <a href="#!">Link 1</a>
                  </li>
                  <li>
                    <a href="#!">Link 2</a>
                  </li>
                  <li>
                    <a href="#!">Link 3</a>
                  </li>
                  <li>
                    <a href="#!">Link 4</a>
                  </li>
                </ul> -->
              </div>
              <!-- Grid column -->
              <!-- Grid column -->
              <div class="col-md-3 mb-md-0 mb-3">
                <!-- Links
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                  <li>
                    <a href="#!">Link 1</a>
                  </li>
                  <li>
                    <a href="#!">Link 2</a>
                  </li>
                  <li>
                    <a href="#!">Link 3</a>
                  </li>
                  <li>
                    <a href="#!">Link 4</a>
                  </li>
                </ul>-->
              </div>
              <!-- Grid column -->
            </div>
            <!-- Grid row -->
          </div>
          <!-- Footer Links -->
          <!-- Copyright -->
          <div class="footer-copyright text-center py-3">
            <a href="https://mdbootstrap.com/education/bootstrap/"></a>
          </div>
          <!-- Copyright -->
        </footer>
        <!-- Footer -->

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </body>

</html>

stats/templates/stats/compare.html
<!doctype html>

{% load static %}
{% load humanize %}

<html>

    <head>
        <meta charset="'utf-8">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'stats/compare.css' %}">

       <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">-->
        <script src="https://kit.fontawesome.com/ecc9da9fa7.js"></script>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

        <title></title>
    </head>

    <body>

        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <a href="{% url 'stats:index' %}" class="navbar-brand">Kpop-Numbers</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:groups' %}">Artists</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:graph' 'all' %}">Graphs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stats:data' %}">Data</a>
                    </li>
                </ul>
            </div>
            <form action="/groups/" class="form-inline my-2 my-lg-0">
                <input id="search_box" name="search" class="form-control mr-sm-2" type="search" placeholder="Search for artist" aria-label="Search">
                <button id="search_submit" class="btn btn-outline-warning my-2 my-sm-0" type="search">Search</button>
            </form>
        </nav>

        <h3 id="comparewith" align="center">Compare {{name}} with:</h3>

        <div id="FilterBy" class="container-fluid jumbotron">
            <div class="row" id="buttons">
                <div class="col">
                    <h3><i class="fas fa-venus-mars"></i> Gender</h3>
                    <div id="genderBtnContainer">
                        <button class="btn gactive" onclick="filterSelection('anyGender','gender')"> Any</button>
                        <button class="btn" onclick="filterSelection('B','gender')"> Boys</button>
                        <button class="btn" onclick="filterSelection('G','gender')"> Girls</button>
                    </div>
                </div>

                <div class="col">
                <h3><i class="far fa-building"></i> Company</h3>
                    <div class="dropdown">
                      <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-flip="false" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Any
                      </button>
                      <ul class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenuButton">
                          <li><button class="dropdown-item" type="button" onclick="filterSelection('anyCompany','company')"> Any</button></li>
                          {% for c in company_list %}
                              <li><button class="dropdown-item" type="button" onclick="filterSelection('{{ c.company }}','company')"> {{ c.company }}</button></li>
                          {% endfor %}
                      </ul>
                    </div>
                </div>

                <div class="col">
                    <h3><i class="fas fa-users"></i> Members</h3>
                    <div id="slider-range"></div>
                    <h5 id="amount"></h5>
                </div>

                <div class="col dropdown">
                    <h3>&nbsp;</h3>
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if sort == "Most Viewed"%}
                        <i class="far fa-eye"></i>
                        {% elif sort == "Hottest" %}
                            <i class="fab fa-hotjar"></i>
                        {% elif sort == "Alphabetical" %}
                            <i class="fas fa-sort-alpha-down"></i>
                        {% elif sort == "Oldest" %}
                            <i class="fas fa-hourglass-end"></i>
                        {% elif sort == "Newest" %}
                            <i class="fas fa-baby"></i>
                        {% endif %}
                        {{ sort }}
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'stats:compare' opk name %}"><i class="far fa-eye"></i> Most Viewed</a>
                        <a class="dropdown-item" href="{% url 'stats:comparehottest' opk name %}"><i class="fab fa-hotjar"></i> Hottest</a>
                        <a class="dropdown-item" href="{% url 'stats:comparealphabetical' opk name %}"><i class="fas fa-sort-alpha-down"></i> Alphabetical</a>
                        <a class="dropdown-item" href="{% url 'stats:compareoldest' opk name %}"><i class="fas fa-hourglass-end"></i> Oldest</a>
                        <a class="dropdown-item" href="{% url 'stats:comparenewest' opk name %}"><i class="fas fa-baby"></i> Newest</a>
                    </div>
                </div>
            </div>
        </div>

        <h5 id="display">Showing <span id="counting">displaying</span> artists:</h5>


        <div class="container-fluid">
            <div class="row" id="groups">
            {% for g in object_list %}
                 <div class="col-xs-2 col-xs-offset-5 filterDiv {{ g.gender }} {{ g.company }} {{ g.current_member_count }} anyGender anyCompany anyMemberCount choose">
                     <a href="{% url 'stats:comparing' opk g.pk %}">
                         <div class="card bg-dark">
                             <img src="{{ g.pic_url }}" class="card-img-top" alt="...">
                             <div class="card-img-overlay">
                                 <h5 class="groupname card-text">{{ g }}</h5>
                                 <p class="viewcount card-text"><i class="far fa-eye"></i> &nbsp;{{ g.total_view_count|intcomma }}</p>
                             </div>
                         </div>
                     </a>
                 </div>
            {% endfor %}
            </div>
        </div>

         <!-- Footer -->
        <footer class="page-footer font-small blue pt-4">
          <!-- Footer Links -->
          <div class="container-fluid text-center text-md-left">
            <!-- Grid row -->
            <div class="row">
              <!-- Grid column -->
              <div class="col-md-6 mt-md-0 mt-3">
                <!-- Content -->
                <h5 class="text-uppercase">Contact</h5>
                <p>aaronmitchellharris@gmail.com</p>
              </div>
              <!-- Grid column -->
              <hr class="clearfix w-100 d-md-none pb-3">
              <!-- Grid column -->
              <div class="col-md-3 mb-md-0 mb-3">
                  <img src="https://developers.google.com/youtube/images/developed-with-youtube-sentence-case-dark.png" alt="..." width="400" height="143">
                <!-- Links
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                  <li>
                    <a href="#!">Link 1</a>
                  </li>
                  <li>
                    <a href="#!">Link 2</a>
                  </li>
                  <li>
                    <a href="#!">Link 3</a>
                  </li>
                  <li>
                    <a href="#!">Link 4</a>
                  </li>
                </ul> -->
              </div>
              <!-- Grid column -->
              <!-- Grid column -->
              <div class="col-md-3 mb-md-0 mb-3">
                <!-- Links
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                  <li>
                    <a href="#!">Link 1</a>
                  </li>
                  <li>
                    <a href="#!">Link 2</a>
                  </li>
                  <li>
                    <a href="#!">Link 3</a>
                  </li>
                  <li>
                    <a href="#!">Link 4</a>
                  </li>
                </ul>-->
              </div>
              <!-- Grid column -->
            </div>
            <!-- Grid row -->
          </div>
          <!-- Footer Links -->
          <!-- Copyright -->
          <div class="footer-copyright text-center py-3">
            <a href="https://mdbootstrap.com/education/bootstrap/"></a>
          </div>
          <!-- Copyright -->
        </footer>
        <!-- Footer -->

        <script src="{% static 'stats/compare.js' %}"></script>

        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </body>

</html>